### ISSUE TITLE
Python 3.6?

### ISSUE THREAD

**Issue by haraldschilly** [leanprover-community/format_lean#5]
I've looked at deploying this on cocalc, but the python 3.7 dependency isn't given without much extra work. I saw there are just two mall usages of that `@dataclass`. Despite that it is a cool new feature, maybe we could go back to the traditional style and make installing it much easier? 

Besides that, is there are test to run? To me this looks like something where a small test with integration to travis-ci could be worthwhile to add.

**Comment by PatrickMassot** [comment]
I know @kbuzzard is very enthusiastic about this project, but it's really at the prototype stage. So I think we should wait a bit before deploying this anywhere. And I don't really know how this could be used on CoCalc, this is a static tool producing html files from lean files, but not in real time.

Actually there are  currently 13 uses of @dataclass in the code base (I don't know how you get that number 2). Of course these could be removed easily, I only use it in order to save boilerplate in `__init__`, I'm not even using any other autogenerated magic method. So I'll get rid of them if needed at some point.

Of course I agree there should be tests. I even have a test directory here, but it's not part of the git repository because it's currently empty...

**Comment by haraldschilly** [comment]
> prototype stage

ok, I see!

> 13 uses

well, that's more. I used github's search here, that's all.

> I don't really know how this could be used on CoCalc

me neither, but it is possible to run this in a project and then publicly serve static html pages.

**Comment by PatrickMassot** [comment]
I think GitHub search told you `@dataclass` is used in two *files*, but one of them uses it twelve times.
