### ISSUE TITLE
lean to other formal language

### ISSUE THREAD

**Issue by arademaker** [leanprover-community/format_lean#8]
Would be possible to use ideas from here to produce TPTP (http://tptp.org) from Lean files? Of course, the transformation would need to deal with the proper mapping from dependent types to FOL, THF  etc.

**Comment by PatrickMassot** [comment]
I'm sorry I didn't see this question earlier. This project is mostly about turning Lean files into something easier to read for humans. What you want seems to require a lot more Lean meta-programming. The good news is translating to FOL is also useful in order to use SMT solvers. You should ask @gebner what is the current status of that, and whether  he would be interested in this TPTP thing.

**Comment by gebner** [comment]
Yes, for leanhammer I'm producing TPTP files.  This is still a bit work-in-progress though.  There are translations to both [FOL](https://github.com/gebner/mathlib/blob/e7f1b800744ba334c8ef1f678b7e20fc63762dfa/src/tactic/hammer/fo_translation2.lean) and [THF](https://github.com/gebner/mathlib/blob/e7f1b800744ba334c8ef1f678b7e20fc63762dfa/src/tactic/hammer/monomorphization2.lean) in my mathlib branch.  The first-order translation is somewhat similar to to the one described in the coqhammer paper, although I've been experimenting with omitting type-class instances.  (If you want to try it out you'll need my [lean branch](https://github.com/gebner/lean/tree/9f47061720a5f46f4eca8dfef53492617711ee45) as well.)  [Here is an example of a TPTP file produced by the FOL translation.](https://gist.github.com/gebner/1f574c5fe06319fdbefee35e82dfeabb)
